### ISSUE TITLE
filter::signatures mangles line numbers in code with heredocs

### ISSUE THREAD

**Issue by wchristian** [Perl-GPU/OpenGL-Modern#17]
This can be fixed either in OpenGL.pm by replacing all HEREDOCs with normal strings, removing filter::signatures, or contributing to a fix in f::s directly: https://github.com/Corion/filter-signatures/issues/2

**Comment by devel-chm** [comment]
Per the suggestion by Corion and since the code is being automatically generated removing the use of signatures is the simplest fix.

**Comment by devel-chm** [comment]
The use of function signatures has been eliminated in the chm_generate-XS_work branch which targets improvements to the automatic code generation:

- Name routines with * or [] arguments as glXXX_c
- Good routines (no pointer or []) are named glXXX since the default XS bindings are correct
- Implement _p bindings (glUniform#xv for example)
- Implement _r bindings where _r is a ref to something (object?)
