### ISSUE TITLE
do we want error handling to be mostly user-side or code-side?

### ISSUE THREAD

**Issue by wchristian** [Perl-GPU/OpenGL-Modern#43]
I got thinking about this looking at your most recent commit, containing this:

        RETVAL = glewInit();
        if ( !RETVAL )
            _done_glewInit++;
    OUTPUT:
        RETVAL

It would be nicer for the user if that would do the following instead:

   croak( "Error %d while initializing glut.", RETVAL );

However while pondering about this, i thought it might be good to decide on one facet of handling and try to do that one as much as possible.

What are your thoughts on this?

**Comment by devel-chm** [comment]
This seems to duplicate issue #36 which was left open because I think the user should not have to know internal details of GLEW to have OpenGL::Modern do the right thing.  That part has not been completed.  In general, we should support "raw" error handling a la C OpenGL API and with additional perl-ish error handing with better error messages where possible assuming no significant performance penalty.

**Comment by wchristian** [comment]
This question is a superset of the one posed in #36, i guess.

I read your response as "in general i prefer to have things die rather than return error"?
