### ISSUE TITLE
t/0999_tidy.t causing FAIL reports

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-Modern#56]
[For example](http://www.cpantesters.org/cpan/report/2427933a-4478-11e7-ba85-3499dde9cdd7)

> "/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.12.0/89ad/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Modern.bs blib/arch/auto/OpenGL/Modern/Modern.bs 644
PERL_DL_NONLAZY=1 "/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.12.0/89ad/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_basic.t ................... ok
t/01_context.t ................. ok
t/02_glew_version_accessors.t .. skipped: glewContext did not succeed, skipping live tests
t/02_glGetShaderInfoLog.t ...... ok
Deep recursion on subroutine "IO::All::AUTOLOAD" at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.12.0/89ad/lib/site_perl/5.12.0/IO/All.pm line 100.
Out of memory!
Out of memory!
Out of memory!
t/0999_tidy.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run

**Comment by devel-chm** [comment]
@wchristian - any ideas?

**Comment by wchristian** [comment]
This doesn't make any sense to me. There is no way that line should throw that kind of error.

However i do not know if i'm looking at the right version of the module, particularly since EUMM seems to have failed to identify it:

        IO::All                       0     0      

I see two possible things to do here:

1. Add a "report all versions of the dep modules" test like i see in a lot of ether's releases.
2. Require a current version of IO::All.

Probably both might be a good idea. Your thoughts?

**Comment by devel-chm** [comment]
Sounds good to me.  I'm working on OpenGL::GLFW bindings to GLFW3 at the moment and expect to get some time for another push at OpenGL::Modern implementation.  I'm going to YAPC::NA 2017 next week and maybe can find some folks interested and willing to help.

**Comment by mohawk2** [comment]
I have removed this test, since on its very best day it is relevant to the module author.
